# include subparts of the Admin interface
_admin_product_routing:
    resource: "admin/routing_product.yml"
    prefix: /product

_admin_category_routing:
    resource: "admin/routing_category.yml"
    prefix: /category

_admin_module_routing:
    resource: "admin/routing_module.yml"
    prefix: /module

# include common routes for Admin interface
admin_common_pagination:
    path:     /common/pagination/{offset}/{limit}/{total}
    methods:  [GET]
    defaults:
        _controller: 'PrestaShopBundle\Controller\Admin\CommonController::paginationAction'
        offset: 0
        limit: 10
        total: 0
    requirements:
        offset: \d+
        limit: \d+
        total: \d+

admin_common_upload:
    path:     /common/upload/{file_type}
    methods:  [POST]
    defaults: { _controller: 'PrestaShopBundle\Controller\Admin\CommonController::uploadAction', file_type: image }
    requirements:
        file_type:  image|file
